app:
  name: AppName
  protocol: http/https
authentication:
  key: service_key
rest:
  host: hast_name
  port: port_number
grpc:
  host: hast_name
  port: port_number
smtp:
  host: smtp.host
  port: 111
  username: example@email.com
  password: email-password
db:
  uri: mongo-db-uri
