app: AppName
authentication_key: service_key
email_verification_endpoint: http://localhost:2222/
grpc:
  host: hast_name
  port: port_number
db:
  uri: mongo-db-uri
smtp:
  host: smtp.host
  port: 111
  username: example@email.com
  password: email-password
