app: QuaDevAuthenticationTest
authentication_key: test_key
email_verification_endpoint: http://localhost:2222/
grpc:
  host: localhost
  port: 3333
db:
  uri: mongodb+srv://password:user@cluster.test.mongodb.net/test
smtp:
  host: localhost
  port: 1111
  username: test@test.com
  password: test_password
rest:
  host: localhost
  port: 4444